#!/usr/bin/ruby
 
begin
  require 'hirb' # sudo gem install cldwalker-hirb --source http://gems.github.com
  Hirb.enable
rescue LoadError
end

require 'logger'
Object.const_set('RAILS_DEFAULT_LOGGER', Logger.new(STDOUT))